public class addition 
{
    public static void addition(integer a, integer b)
    {
        integer c = (a+b);
    system.debug(' add of two numbers= '+ c);
    }
    public static void percentage(integer x,integer y, integer z, integer k, integer l)
        {
            integer g=(x+y+z+k+l);
            integer h = ((g*100)/500);
            system.debug(' total marks= '+g);
            system.debug(' percentage of total marks= '+h);
        }
}