public class comp2strings 
{
    public static void examp(string a,string b)
    {
        integer length1=a.length();
        integer length2=b.length();
        system.debug(length1);
        system.debug(length2);
        if(length1==length2)
        {
            system.debug('two string are equal');
        }
        else
        {
            system.debug('two string are not equal');
        }
    }

}