public class demo2501 {
    public static void addnumbers(){
        //integer class: 0-9
        //string class: a-z
        integer a=3;
        integer b=6;
        integer result=a+b;
        system.debug('sub of two numbers = '+result);
    }
public static void addnumbers1(integer a,integer b){
        integer result=a+b;
        system.debug('add of two numbers = '+result);
    }
    public static void greetings(string c){
        string a='hello macha';
        string b=' how are you';
        system.debug(a+b+c);
    }
}