public class extendedIngredients {
private integer id;
    public void setid(integer id){
        this.id=id;
    }
    public integer getid(){
        return id;
    }
    private string image;
    public void setimage(string image){
        this.image=image;
    }
    public string getimage(){
        return image;
    }
    private string name;
    public void setname(string name){
        this.name=name;
    }
    public string getname(){
        return name;
    }
}