public class AntraEmployeeConsumerProgramWrapper {
    Private string ename;
    public void setename(string ename){
        this.ename=ename;
    }
    public string getename(){
        return ename;
    }
    Private string empname;
    public void setempname(string empname){
        this.empname=empname;
    }
    public string getempname(){
        return empname;
    }
   Private string empid;
    public void setempid(string empid){
        this.empid=empid;
    }
    public string getempid(){
        return empid;
    } 
    Private string empemail;
    public void setempemail(string empemail){
        this.empemail=empemail;
    }
    public string getempemail(){
        return empemail;
    } 
}