public class AntraAccountConsumerProgramWrapper {
private string name;
    public void setname(string name){
        this.name=name;
    }
    public string getname(){
        return name;
    }
    private string id;
    public void setid(string id){
        this.id=id;
    }
    public string getid(){
        return id;
    }
    private string AccountNumber;
    public void setAccountNumber(string AccountNumber){
        this.AccountNumber=AccountNumber;
    }
    public string getAccountNumber(){
        return AccountNumber;
    }
    private string Site;
    public void setSite(string Site){
        this.Site=Site;
    }
    public string getSite(){
        return Site;
    }
}